apiVersion: apps/v1
kind: Deployment
metadata:
  name: oktfhs2gfh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oktfhs2gfh
  template:
    metadata:
      labels:
        app: oktfhs2gfh
    spec:
      containers:
      - image: okteto.dev/oktfhs2gfh:latest
        name: oktfhs2gfh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: ParameterSSENCYPT
          value: "chacha20-ietf-poly1305"
        - name: Vless_UUID
          value: "75ddc1ee-e121-42ae-a1c2-07fd3da89bad"
        - name: Vless_Path
          value: "/75ddc1ee-e121-42ae-a1c2-07fd3da89bad-vless"
        - name: Vmess_UUID
          value: "75ddc1ee-e121-42ae-a1c2-07fd3da89bad"
        - name: Vmess_Path
          value: "/75ddc1ee-e121-42ae-a1c2-07fd3da89bad-vmess"
        - name: Trojan_UUID
          value: "75ddc1ee-e121-42ae-a1c2-07fd3da89bad"
        - name: Trojan_Path
          value: "/75ddc1ee-e121-42ae-a1c2-07fd3da89bad-trojan"
        - name: SS_UUID
          value: "75ddc1ee-e121-42ae-a1c2-07fd3da89bad"
        - name: SS_Path
          value: "/75ddc1ee-e121-42ae-a1c2-07fd3da89bad-ss"
        - name: Share_Path
          value: "/75ddc1ee-e121-42ae-a1c2-07fd3da89bad-share"
