apiVersion: v1
kind: Service
metadata:
  name: oktfhs2gfh
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "oktfhs2gfh"
    port: 8080
  selector:
    app: oktfhs2gfh
